travis:
  secure:
    BINSTAR_TOKEN: GAX57cDvRjVraH8h5UJXX8vi3YLAV/568rrCFhZyiUNbT/rsDHlkiA8bviFmOas2wjeMAR3qQdMt6/9XLW9szBnsVmWZ+hoERQqMUWVx4DQOJWqC5+fBOhTUlv5fG9/zhUtexi02BUoAuR3kYs5ycLLGHt+zf7GbAEGALa51Aw88VL9SPApbpGYE91vfh5Xgm4OuIsdZy0PrzqWu6Pa66rzbOPYcQ6SApOYlplY1VCXemKGtztCORxeOxrf0ehwP5lBfFCCUWtgjbDY4RSrU4TD9hqAQlDLCzDkrt0KCVdw78qSWjRSxr0ri6v87mbIs0WrUM/RtLH2eiKEqsQFNa4xhkbRr5abxcwjbvfGW0q/Kb0Fq+mhFt2Bp3baK1bZLlZUUvQegqv350TfNLLDuSZDDAq23DOueQ8TwExEgNOqUBXua+Ga0KzNa03zRHyUKLtqXGpPr0CaH/Ve5VDeUkCvzThpCzlnJGtEHeJS/xVBc4tpIyGKIu4uevdCa6JC2hPYL4t4/3AELcoa0+2y8+FiDJ+tZxhloy6zPAxBc9JJIelKaJtRWBFBwXEirMOFW3pJJ+F+QWpYSfusqyrUdDKYV0V4f97HztEsxKJAY1+ziwIkL4hQd/iVaWyXzvugUpAdyGqSQfx2wTgfTF1pw726+3BADTYLJHQMfyMiX/1g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
